# Generated by Django 4.1.1 on 2022-11-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf", "0002_products_stock_alter_products_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Revenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=50)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name=(
                            ("MPESA", "MPESA"),
                            ("NHIF", "NHIF"),
                            ("CASH", "CASH"),
                            ("BANK", "BANK"),
                        ),
                    ),
                ),
                ("registration", models.FloatField(blank=True, default=0.0, null=True)),
                ("laboratory", models.FloatField(blank=True, default=0.0, null=True)),
                ("radiology", models.FloatField(blank=True, default=0.0, null=True)),
                ("pharmacy", models.FloatField(blank=True, default=0.0, null=True)),
                ("procedure", models.FloatField(blank=True, default=0.0, null=True)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Products",
        ),
    ]
